before_script:
- ./run-gen
matrix:
  include:
  - name: c-scanf1
    language: cpp
    script:
    - (cd ./c-scanf1; ./build)
    after_success:
    - ./run ./large.txt ./c-scanf1/a.out
  - name: cin1
    language: cpp
    script:
    - (cd ./cin1; ./build)
    after_success:
    - ./run ./large.txt ./cin1/a.out
  - name: scan1
    language: rust
    rust: stable
    script:
    - (cd ./scan1; cargo build --release)
    after_success:
    - ./run ./large.txt ./scan1/target/release/scan1
  - name: rust-read1
    language: rust
    rust: stable
    script:
    - (cd ./rust-read1; cargo build --release)
    after_success:
    - ./run ./large.txt ./rust-read1/target/release/rust-read1
