language: rust
rust:
- stable
script:
- ./build
after_success:
- ./run ./large.txt $BIN
matrix:
  include:
  - name: c-scanf1
    env: BIN=./c-scanf1/a.out
  - name: cin1
    env: BIN=./cin1/a.out
  - name: scan1
    env: BIN=./scan1/target/release/scan1
