#!/bin/bash

set -xeu

build () {
    (cd ./c-scanf1; ./build)
    (cd ./cin1; ./build)
    (cd ./scan1; cargo build --release)
    (cd ./rust-read1; cargo build --release)
}

run () {
    time (cat "$1" | ./c-scanf1/a.out)
    time (cat "$1" | ./cin1/a.out)
    time (cat "$1" | ./scan1/target/release/scan1)
    time (cat "$1" | ./rust-read1/target/release/rust-read1)
}

./run-gen
build
run './small.txt'
run './large.txt'
