#!/bin/bash

set -xeu

generate_input () {
    g++ --std=c++1y -O2 -Wall -o ./gen/a.out ./gen/gen.cpp
    ./gen/a.out > ./small.txt
    ./gen/a.out --large > ./large.txt
}

build () {
    (cd ./cin1; ./build)
    (cd ./scan1; cargo build --release)
}

generate_input
build
